name: Saham Daily Bot

on:
  schedule:
    # Berjalan Senin-Jumat jam 18.40 WITA (10:40 UTC)
    - cron: "40 10 * * 1-5"
  workflow_dispatch: # Memungkinkan tombol 'Run manual'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Menggunakan versi terbaru agar kompatibel

      - name: Install Dependencies
        run: pip install pandas yfinance pandas-ta requests

      - name: Run Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot_saham.py
